require 'zero-one-bot/commands/base'
require 'zero-one-bot/commands/advice'
require 'zero-one-bot/commands/help'
require 'zero-one-bot/commands/list'
require 'zero-one-bot/commands/memo'
require 'zero-one-bot/commands/output'
require 'zero-one-bot/commands/tip'
require 'zero-one-bot/commands/erai'
